2024-02-20 23:54:06,774 - app.log - ERROR - ERROR: cannot make dir /home/h4438/Desktop/graduate/WebQA/core/instance
2024-02-20 23:57:21,994 - app.log - ERROR - [APP] answer_major went wrong!
Traceback (most recent call last):
  File "/home/h4438/Desktop/graduate/WebQA/core/app.py", line 72, in answer_major
    "answer": rag_resp.answer,
AttributeError: 'str' object has no attribute 'answer'
2024-02-21 00:01:17,067 - app.log - ERROR - [APP] answer_major went wrong!
Traceback (most recent call last):
  File "/home/h4438/Desktop/graduate/WebQA/core/app.py", line 69, in answer_major
    rag_resp = bot.answer(escape(question))
  File "/home/h4438/miniconda3/envs/uni/lib/python3.9/site-packages/langsmith/run_helpers.py", line 453, in wrapper
    raise e
  File "/home/h4438/miniconda3/envs/uni/lib/python3.9/site-packages/langsmith/run_helpers.py", line 449, in wrapper
    function_result = func(*args, **kwargs)
  File "/home/h4438/Desktop/graduate/WebQA/core/src/robot.py", line 106, in answer
    self.__update_followup(content=resp.document)
TypeError: __update_followup() got an unexpected keyword argument 'content'
2024-02-21 00:03:02,606 - app.log - ERROR - ERROR: cannot make dir /home/h4438/Desktop/graduate/WebQA/core/instance
